### PR TITLE
Quoutes around path, so build can be done safely even if there are spaces in path

### PR DESCRIPTION
**Pull request by keybreak**
I believe this is very important fix, because if you don't use quotes around any path (especially for `mv`, `rm`) - it could be super dangerous for builder.

You never know what path user is running in his environment and what kind of symbols it could have, including space, for example if your disk have space, something like:

~~~bash
/run/media/user/temp disk
~~~

So, it's just a very bad bar programmer's karma to not use quotes around any path, let's not do that anymore for safety, even when it seemingly doesn't make sense - it's a very good practice to have!

I've looked in archiso code and they have done it already, so i've took my liberty to fix EndeavourOS specific scripts, now iso can be built anywhere, at least as far as i have personally just tested, even if path have spaces! :partying_face: 

Please review and test it too, in case i've missed something.

I'm not completely sure about some glob stuff proper syntax, like:
**fix_permissions.sh** line 9
~~~bash
chmod +x "./"{mkarchiso,run_before_squashfs.sh}
~~~

**run_before_squashfs.sh** line 43
~~~bash
chmod +x \"/home/liveuser/.local/bin\"/*
~~~

**run_before_squashfs.sh** line 64
~~~bash
chmod 644 \"/usr/share/endeavouros\"/*.png
~~~

But it builds without errors, so i assume this places are working as well.

P.S. Also i've changed `#!/bin/bash` to `#!/usr/bin/env bash` everywhere, just for consistency :upside_down_face:

### CODE REVIEW

**Comment by killajoe** [comment]
Looks good to me!  let's wait for @manuel-192 to have a look to validate the changes.

**Comment by keybreak** [comment]
@killajoe 
For those 3 cases i felt iffy about, i've consulted **Kresimir**, and that should be safer way of writing those:

**fix_permissions.sh** line 9
~~~
chmod +x "./"{"mkarchiso","run_before_squashfs.sh"}
~~~

**run_before_squashfs.sh** line 43
~~~bash
chmod +x \"/home/liveuser/.local/bin/\"*
~~~

**run_before_squashfs.sh** line 64
~~~bash
chmod 644 \"/usr/share/endeavouros/\"*\".png\"
~~~

If you accept  - you can fix it afterwards, or i can create another request later :upside_down_face:

**Comment by killajoe** [comment]
can you put the 3 extra changes in your gork and do a new pr ?

**Comment by keybreak** [comment]
Sure, i'll try...Not to break anything as well :laughing:

**Pull request closed without merging**
